# Generated by Django 5.1.4 on 2026-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='index_sql',
            field=models.TextField(blank=True, default='', help_text='CREATE INDEX statements for the indexed instance'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='seed_sql_large',
            field=models.TextField(blank=True, default='', help_text='Extra seed SQL for the large dataset instance'),
        ),
    ]
