# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_challenge_index_sql_challenge_seed_sql_large'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='materialized_schema_sql',
            field=models.TextField(blank=True, default='', help_text='CREATE TABLE statements only (no functions)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='materialized_seed_sql',
            field=models.TextField(blank=True, default='', help_text='Deterministic INSERT statements generated from seed_sql'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='expected_output',
            field=models.JSONField(blank=True, help_text='Snapshot of ground truth output (columns + rows)', null=True),
        ),
    ]
