# Generated by Django 5.1.4 on 2026-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_materialize_challenge_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='index_sql',
            field=models.TextField(blank=True, default='', help_text='CREATE INDEX statements for the large-indexed instance'),
        ),
    ]
