# Generated by Django 5.1.4 on 2026-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_challenge_index_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='index_sql',
            field=models.TextField(blank=True, default='', help_text='CREATE INDEX statements for the indexed instance'),
        ),
    ]
