from api.models import Challenge


CHALLENGE = {
    "title": "Course Prerequisite Chains",
    "description": (
        "Find the longest prerequisite chain for each department \u2014 the maximum depth "
        "of courses you must take sequentially before reaching any given course. "
        "Return department name, the course at the end of the longest chain, and the "
        "chain length. Only consider departments with chains of depth >= 3.\n\n"
        "Hint: The enrollments table exists in the schema but is not needed for the "
        "correct answer. The prerequisite graph is small \u2014 traverse it first.\n\n"
        "Large dataset: 500 courses, ~2k prerequisite edges, 800k enrollments."
    ),
    "difficulty": "hard",
    "schema_sql": (
        "CREATE TABLE departments (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    name VARCHAR(100) NOT NULL,\n"
        "    faculty VARCHAR(100)\n"
        ");\n\n"
        "CREATE TABLE courses (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    department_id INT REFERENCES departments(id),\n"
        "    code VARCHAR(20) NOT NULL,\n"
        "    title VARCHAR(200) NOT NULL,\n"
        "    credits INT\n"
        ");\n\n"
        "CREATE TABLE prerequisites (\n"
        "    course_id INT REFERENCES courses(id),\n"
        "    prerequisite_id INT REFERENCES courses(id),\n"
        "    PRIMARY KEY (course_id, prerequisite_id)\n"
        ");\n\n"
        "CREATE TABLE enrollments (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    student_id INT,\n"
        "    course_id INT REFERENCES courses(id),\n"
        "    semester VARCHAR(20),\n"
        "    grade VARCHAR(5)\n"
        ");"
    ),
    "seed_sql": (
        "INSERT INTO departments (name, faculty) VALUES\n"
        "  ('Computer Science', 'Engineering'),\n"
        "  ('Mathematics', 'Science'),\n"
        "  ('Physics', 'Science'),\n"
        "  ('Electrical Engineering', 'Engineering'),\n"
        "  ('Philosophy', 'Arts');\n\n"
        "INSERT INTO courses (department_id, code, title, credits) VALUES\n"
        "  (1, 'CS1010', 'Intro to Programming', 4),\n"
        "  (1, 'CS2030', 'OOP', 4),\n"
        "  (1, 'CS2040', 'Data Structures', 4),\n"
        "  (1, 'CS3230', 'Algorithms', 4),\n"
        "  (1, 'CS4234', 'Advanced Algorithms', 4),\n"
        "  (2, 'MA1101', 'Linear Algebra', 4),\n"
        "  (2, 'MA1102', 'Calculus I', 4),\n"
        "  (2, 'MA2101', 'Linear Algebra II', 4),\n"
        "  (2, 'MA2104', 'Multivariable Calculus', 4),\n"
        "  (2, 'MA3201', 'Abstract Algebra', 4),\n"
        "  (3, 'PC1101', 'Physics I', 4),\n"
        "  (3, 'PC1102', 'Physics II', 4),\n"
        "  (3, 'PC2130', 'Quantum Mechanics', 4),\n"
        "  (3, 'PC3130', 'Advanced QM', 4),\n"
        "  (4, 'EE1101', 'Circuits I', 4),\n"
        "  (4, 'EE2101', 'Circuits II', 4),\n"
        "  (4, 'EE3101', 'Signal Processing', 4),\n"
        "  (5, 'PH1101', 'Intro to Philosophy', 4),\n"
        "  (5, 'PH2201', 'Ethics', 4),\n"
        "  (5, 'PH2202', 'Logic', 4);\n\n"
        "-- Prerequisite chains:\n"
        "-- CS: CS1010 -> CS2030 -> CS2040 -> CS3230 -> CS4234 (depth 5)\n"
        "-- MA: MA1101 -> MA2101 -> MA3201 (depth 3), MA1102 -> MA2104 (depth 2)\n"
        "-- PC: PC1101 -> PC1102 -> PC2130 -> PC3130 (depth 4)\n"
        "-- EE: EE1101 -> EE2101 -> EE3101 (depth 3)\n"
        "-- PH: PH1101 -> PH2201 (depth 2), PH1101 -> PH2202 (depth 2)\n"
        "INSERT INTO prerequisites (course_id, prerequisite_id) VALUES\n"
        "  (2, 1), (3, 2), (4, 3), (5, 4),\n"
        "  (8, 6), (10, 8),\n"
        "  (9, 7),\n"
        "  (12, 11), (13, 12), (14, 13),\n"
        "  (16, 15), (17, 16),\n"
        "  (19, 18), (20, 18);\n\n"
        "INSERT INTO enrollments (student_id, course_id, semester, grade) VALUES\n"
        "  (1, 1, '2024S1', 'A'), (1, 2, '2024S2', 'B+'),\n"
        "  (2, 6, '2024S1', 'A-'), (2, 8, '2024S2', 'B'),\n"
        "  (3, 11, '2024S1', 'A'), (3, 12, '2024S2', 'A-'),\n"
        "  (4, 15, '2024S1', 'B+'), (4, 16, '2024S2', 'A'),\n"
        "  (5, 18, '2024S1', 'A'), (5, 19, '2024S2', 'B');"
    ),
    "index_sql": (
        "CREATE INDEX idx_prerequisites_course ON prerequisites(course_id);\n"
        "CREATE INDEX idx_prerequisites_prereq ON prerequisites(prerequisite_id);\n"
        "CREATE INDEX idx_enrollments_course_semester ON enrollments(course_id, semester);"
    ),
    "seed_sql_large": (
        "SELECT setseed(0.42);\n\n"
        "-- 50 departments\n"
        "INSERT INTO departments (name, faculty)\n"
        "SELECT 'Department_' || i,\n"
        "  (ARRAY['Engineering','Science','Arts','Business','Medicine'])[1 + (i % 5)]\n"
        "FROM generate_series(6, 50) AS i;\n\n"
        "-- 500 courses (10 per department)\n"
        "INSERT INTO courses (department_id, code, title, credits)\n"
        "SELECT\n"
        "  ((i - 1) / 10) + 1 AS dept_id,\n"
        "  'C' || ((i - 1) / 10 + 1) || '0' || (i % 10) AS code,\n"
        "  'Course_' || i AS title,\n"
        "  (ARRAY[3, 4, 4, 3, 4])[1 + (i % 5)]\n"
        "FROM generate_series(21, 500) AS i;\n\n"
        "-- ~2000 prerequisite edges (DAG: only lower id -> higher id within same dept)\n"
        "INSERT INTO prerequisites (course_id, prerequisite_id)\n"
        "SELECT DISTINCT c2.id, c1.id\n"
        "FROM courses c1\n"
        "JOIN courses c2 ON c2.department_id = c1.department_id\n"
        "  AND c2.id = c1.id + 1\n"
        "  AND c2.id > 20\n"
        "WHERE random() < 0.85;\n\n"
        "-- Also add some skip-one edges for branching\n"
        "INSERT INTO prerequisites (course_id, prerequisite_id)\n"
        "SELECT DISTINCT c2.id, c1.id\n"
        "FROM courses c1\n"
        "JOIN courses c2 ON c2.department_id = c1.department_id\n"
        "  AND c2.id = c1.id + 2\n"
        "  AND c2.id > 20\n"
        "WHERE random() < 0.3\n"
        "ON CONFLICT DO NOTHING;\n\n"
        "-- 800k enrollments across 10k students\n"
        "INSERT INTO enrollments (student_id, course_id, semester, grade)\n"
        "SELECT\n"
        "  (random() * 9999 + 1)::int,\n"
        "  (random() * 499 + 1)::int,\n"
        "  (ARRAY['2023S1','2023S2','2024S1','2024S2','2025S1'])[1 + (random() * 4)::int],\n"
        "  (ARRAY['A+','A','A-','B+','B','B-','C+','C','D','F'])[1 + (random() * 9)::int]\n"
        "FROM generate_series(1, 800000);"
    ),
    "ground_truth_query": (
        "WITH RECURSIVE chain AS (\n"
        "    SELECT c.id AS course_id, c.department_id, c.code, c.title, 1 AS depth\n"
        "    FROM courses c\n"
        "    WHERE NOT EXISTS (\n"
        "        SELECT 1 FROM prerequisites p WHERE p.course_id = c.id\n"
        "    )\n"
        "\n"
        "    UNION ALL\n"
        "\n"
        "    SELECT c.id, c.department_id, c.code, c.title, ch.depth + 1\n"
        "    FROM chain ch\n"
        "    JOIN prerequisites p ON p.prerequisite_id = ch.course_id\n"
        "    JOIN courses c ON c.id = p.course_id\n"
        ")\n"
        "SELECT d.name AS department, ch.code AS course_code, ch.title AS course_title, ch.depth AS chain_length\n"
        "FROM (\n"
        "    SELECT DISTINCT ON (department_id) department_id, code, title, depth\n"
        "    FROM chain\n"
        "    ORDER BY department_id, depth DESC\n"
        ") ch\n"
        "JOIN departments d ON d.id = ch.department_id\n"
        "WHERE ch.depth >= 3\n"
        "ORDER BY ch.depth DESC, d.name;"
    ),
    "time_limit_ms": 10000,
}


def run(stdout, style):
    if Challenge.objects.filter(title=CHALLENGE["title"]).exists():
        stdout.write(f"  '{CHALLENGE['title']}' already exists, skipping.")
        return

    from api.views.challenges import _materialize_challenge

    challenge = Challenge.objects.create(**CHALLENGE)
    _materialize_challenge(challenge)

    stdout.write(style.SUCCESS(f"  Created '{CHALLENGE['title']}' challenge"))
