from api.models import Challenge


CHALLENGE = {
    "title": "Hospital Bed Occupancy",
    "description": (
        "For each hospital ward, calculate the daily bed occupancy rate for every day "
        "in the last 6 months. A bed is 'occupied' if a patient's admission period "
        "(admit_date to discharge_date) overlaps that day. Return ward name, date, "
        "occupied beds, total beds, and occupancy percentage. Include days with 0 "
        "occupancy (gap-fill).\n\n"
        "Large dataset: 200 wards, 600k admissions. Efficient date range overlap "
        "handling is critical."
    ),
    "difficulty": "medium",
    "schema_sql": (
        "CREATE TABLE hospitals (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    name VARCHAR(200) NOT NULL,\n"
        "    city VARCHAR(100)\n"
        ");\n\n"
        "CREATE TABLE wards (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    hospital_id INT REFERENCES hospitals(id),\n"
        "    name VARCHAR(100) NOT NULL,\n"
        "    total_beds INT,\n"
        "    ward_type VARCHAR(50)\n"
        ");\n\n"
        "CREATE TABLE patients (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    name VARCHAR(100) NOT NULL,\n"
        "    date_of_birth DATE,\n"
        "    insurance_type VARCHAR(50)\n"
        ");\n\n"
        "CREATE TABLE admissions (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    patient_id INT REFERENCES patients(id),\n"
        "    ward_id INT REFERENCES wards(id),\n"
        "    admit_date DATE NOT NULL,\n"
        "    discharge_date DATE,\n"
        "    diagnosis_code VARCHAR(20)\n"
        ");"
    ),
    "seed_sql": (
        "INSERT INTO hospitals (name, city) VALUES\n"
        "  ('City General Hospital', 'Springfield'),\n"
        "  ('Riverside Medical Center', 'Shelbyville');\n\n"
        "INSERT INTO wards (hospital_id, name, total_beds, ward_type) VALUES\n"
        "  (1, 'ICU-A', 20, 'ICU'),\n"
        "  (1, 'General-1', 50, 'General'),\n"
        "  (1, 'Pediatrics', 30, 'Pediatrics'),\n"
        "  (2, 'ICU-B', 15, 'ICU'),\n"
        "  (2, 'General-2', 40, 'General'),\n"
        "  (2, 'Maternity', 25, 'Maternity');\n\n"
        "INSERT INTO patients (name, date_of_birth, insurance_type) VALUES\n"
        "  ('John Doe', '1980-05-10', 'Private'),\n"
        "  ('Jane Smith', '1975-08-22', 'Public'),\n"
        "  ('Bob Jones', '1990-01-15', 'Private'),\n"
        "  ('Alice Brown', '2000-11-30', 'None'),\n"
        "  ('Charlie Wilson', '1965-03-05', 'Public'),\n"
        "  ('Diana Lee', '1988-07-19', 'Private'),\n"
        "  ('Eve Taylor', '1995-12-01', 'Public'),\n"
        "  ('Frank Garcia', '1970-09-14', 'Private'),\n"
        "  ('Grace Kim', '2005-04-25', 'None'),\n"
        "  ('Hank Davis', '1960-06-08', 'Public'),\n"
        "  ('Ivy Martinez', '1993-02-28', 'Private'),\n"
        "  ('Jack Anderson', '1985-10-17', 'Public'),\n"
        "  ('Karen Thomas', '1978-08-03', 'Private'),\n"
        "  ('Leo Robinson', '2001-01-20', 'None'),\n"
        "  ('Mia Clark', '1955-12-12', 'Public'),\n"
        "  ('Noah Lewis', '1998-06-30', 'Private'),\n"
        "  ('Olivia Walker', '1982-04-15', 'Public'),\n"
        "  ('Paul Hall', '1972-11-08', 'Private'),\n"
        "  ('Quinn Allen', '2003-09-22', 'None'),\n"
        "  ('Ruby Young', '1968-07-04', 'Public');\n\n"
        "-- Admissions spanning the last 6 months with overlapping stays\n"
        "INSERT INTO admissions (patient_id, ward_id, admit_date, discharge_date, diagnosis_code) VALUES\n"
        "  (1, 1, (CURRENT_DATE - INTERVAL '5 months')::date, (CURRENT_DATE - INTERVAL '5 months')::date + 7, 'A01'),\n"
        "  (2, 1, (CURRENT_DATE - INTERVAL '5 months')::date + 3, (CURRENT_DATE - INTERVAL '5 months')::date + 10, 'A02'),\n"
        "  (3, 2, (CURRENT_DATE - INTERVAL '4 months')::date, (CURRENT_DATE - INTERVAL '4 months')::date + 5, 'B01'),\n"
        "  (4, 2, (CURRENT_DATE - INTERVAL '4 months')::date + 2, (CURRENT_DATE - INTERVAL '4 months')::date + 8, 'B02'),\n"
        "  (5, 3, (CURRENT_DATE - INTERVAL '3 months')::date, (CURRENT_DATE - INTERVAL '3 months')::date + 4, 'C01'),\n"
        "  (6, 3, (CURRENT_DATE - INTERVAL '3 months')::date + 1, (CURRENT_DATE - INTERVAL '3 months')::date + 6, 'C02'),\n"
        "  (7, 4, (CURRENT_DATE - INTERVAL '2 months')::date, (CURRENT_DATE - INTERVAL '2 months')::date + 3, 'D01'),\n"
        "  (8, 4, (CURRENT_DATE - INTERVAL '2 months')::date + 1, (CURRENT_DATE - INTERVAL '2 months')::date + 5, 'D02'),\n"
        "  (9, 5, (CURRENT_DATE - INTERVAL '1 month')::date, (CURRENT_DATE - INTERVAL '1 month')::date + 6, 'E01'),\n"
        "  (10, 5, (CURRENT_DATE - INTERVAL '1 month')::date + 2, (CURRENT_DATE - INTERVAL '1 month')::date + 4, 'E02'),\n"
        "  (11, 6, (CURRENT_DATE - INTERVAL '6 months')::date, (CURRENT_DATE - INTERVAL '6 months')::date + 3, 'F01'),\n"
        "  (12, 6, (CURRENT_DATE - INTERVAL '6 months')::date + 1, (CURRENT_DATE - INTERVAL '6 months')::date + 5, 'F02'),\n"
        "  (13, 1, (CURRENT_DATE - INTERVAL '3 months')::date, (CURRENT_DATE - INTERVAL '3 months')::date + 2, 'A03'),\n"
        "  (14, 2, (CURRENT_DATE - INTERVAL '2 months')::date, (CURRENT_DATE - INTERVAL '2 months')::date + 7, 'B03'),\n"
        "  (15, 3, (CURRENT_DATE - INTERVAL '1 month')::date, (CURRENT_DATE - INTERVAL '1 month')::date + 3, 'C03'),\n"
        "  (16, 1, (CURRENT_DATE - INTERVAL '4 months')::date, (CURRENT_DATE - INTERVAL '4 months')::date + 5, 'A04'),\n"
        "  (17, 2, (CURRENT_DATE - INTERVAL '5 months')::date, (CURRENT_DATE - INTERVAL '5 months')::date + 4, 'B04'),\n"
        "  (18, 4, (CURRENT_DATE - INTERVAL '4 months')::date, (CURRENT_DATE - INTERVAL '4 months')::date + 6, 'D03'),\n"
        "  (19, 5, (CURRENT_DATE - INTERVAL '3 months')::date, (CURRENT_DATE - INTERVAL '3 months')::date + 2, 'E03'),\n"
        "  (20, 6, (CURRENT_DATE - INTERVAL '2 months')::date, (CURRENT_DATE - INTERVAL '2 months')::date + 4, 'F03'),\n"
        "  -- A currently admitted patient (no discharge)\n"
        "  (1, 2, CURRENT_DATE - INTERVAL '3 days', NULL, 'B05'),\n"
        "  (3, 1, CURRENT_DATE - INTERVAL '1 day', NULL, 'A05');"
    ),
    "index_sql": (
        "CREATE INDEX idx_admissions_ward_dates ON admissions(ward_id, admit_date, discharge_date);\n"
        "CREATE INDEX idx_admissions_patient ON admissions(patient_id);"
    ),
    "seed_sql_large": (
        "SELECT setseed(0.42);\n\n"
        "-- 10 hospitals\n"
        "INSERT INTO hospitals (name, city)\n"
        "SELECT 'Hospital_' || i,\n"
        "  (ARRAY['New York','Chicago','Houston','Phoenix','Philadelphia',\n"
        "         'San Antonio','San Diego','Dallas','San Jose','Austin'])[1 + (i % 10)]\n"
        "FROM generate_series(1, 10) AS i\n"
        "ON CONFLICT (id) DO NOTHING;\n\n"
        "-- 200 wards total (20 per hospital)\n"
        "INSERT INTO wards (hospital_id, name, total_beds, ward_type)\n"
        "SELECT\n"
        "  ((i - 1) / 20) + 1,\n"
        "  'Ward_' || i,\n"
        "  (random() * 40 + 10)::int,\n"
        "  (ARRAY['ICU','General','Pediatrics','Maternity','Oncology',\n"
        "         'Cardiology','Neurology','Orthopedics'])[1 + (i % 8)]\n"
        "FROM generate_series(1, 200) AS i\n"
        "ON CONFLICT (id) DO NOTHING;\n\n"
        "-- 5000 patients\n"
        "INSERT INTO patients (name, date_of_birth, insurance_type)\n"
        "SELECT 'Patient_' || i,\n"
        "  '1950-01-01'::date + (random() * 20000)::int,\n"
        "  (ARRAY['Private','Public','None'])[1 + (i % 3)]\n"
        "FROM generate_series(1, 5000) AS i\n"
        "ON CONFLICT (id) DO NOTHING;\n\n"
        "-- 600k admissions spanning 2 years, stays 1-30 days (skewed toward 3-7)\n"
        "INSERT INTO admissions (patient_id, ward_id, admit_date, discharge_date, diagnosis_code)\n"
        "SELECT\n"
        "  (random() * 4999 + 1)::int,\n"
        "  (random() * 199 + 1)::int,\n"
        "  admit,\n"
        "  admit + ((random() * random() * 28 + 1)::int),\n"
        "  'DX' || (random() * 999 + 1)::int\n"
        "FROM (\n"
        "  SELECT '2024-04-01'::date + (random() * 730)::int AS admit\n"
        "  FROM generate_series(1, 600000)\n"
        ") sub;"
    ),
    "ground_truth_query": (
        "SELECT\n"
        "    w.name AS ward_name,\n"
        "    d.day::date AS date,\n"
        "    COUNT(a.id) AS occupied_beds,\n"
        "    w.total_beds,\n"
        "    ROUND(COUNT(a.id) * 100.0 / w.total_beds, 2) AS occupancy_pct\n"
        "FROM wards w\n"
        "CROSS JOIN generate_series(\n"
        "    CURRENT_DATE - INTERVAL '6 months',\n"
        "    CURRENT_DATE,\n"
        "    '1 day'::interval\n"
        ") AS d(day)\n"
        "LEFT JOIN admissions a\n"
        "    ON a.ward_id = w.id\n"
        "    AND a.admit_date <= d.day\n"
        "    AND (a.discharge_date >= d.day OR a.discharge_date IS NULL)\n"
        "GROUP BY w.id, w.name, w.total_beds, d.day\n"
        "ORDER BY w.name, d.day;"
    ),
    "time_limit_ms": 10000,
}


def run(stdout, style):
    if Challenge.objects.filter(title=CHALLENGE["title"]).exists():
        stdout.write(f"  '{CHALLENGE['title']}' already exists, skipping.")
        return

    from api.views.challenges import _materialize_challenge

    challenge = Challenge.objects.create(**CHALLENGE)
    _materialize_challenge(challenge)

    stdout.write(style.SUCCESS(f"  Created '{CHALLENGE['title']}' challenge"))
