from api.models import Challenge


CHALLENGE = {
    "title": "Social Network Influence",
    "description": (
        "Find the top 20 'influential' users \u2014 users whose posts received the most "
        "engagement (likes + comments) from users outside their direct friend circle. "
        "Return user display name, post count, total engagement from non-friends, and "
        "the ratio of non-friend to total engagement. Only count users with at least 5 "
        "posts and at least 100 total engagements.\n\n"
        "Large dataset: 10k users, 1M friendships, 500k posts, 2M engagements. "
        "The anti-join pattern (NOT IN vs LEFT JOIN vs NOT EXISTS) makes or breaks "
        "performance here."
    ),
    "difficulty": "hard",
    "schema_sql": (
        "CREATE TABLE users (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    username VARCHAR(50) NOT NULL,\n"
        "    display_name VARCHAR(100) NOT NULL,\n"
        "    joined_at DATE,\n"
        "    is_verified BOOLEAN DEFAULT FALSE\n"
        ");\n\n"
        "CREATE TABLE friendships (\n"
        "    user_id INT REFERENCES users(id),\n"
        "    friend_id INT REFERENCES users(id),\n"
        "    PRIMARY KEY (user_id, friend_id)\n"
        ");\n\n"
        "CREATE TABLE posts (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    user_id INT REFERENCES users(id),\n"
        "    content TEXT,\n"
        "    created_at TIMESTAMP,\n"
        "    category VARCHAR(50)\n"
        ");\n\n"
        "CREATE TABLE engagements (\n"
        "    id SERIAL PRIMARY KEY,\n"
        "    post_id INT REFERENCES posts(id),\n"
        "    user_id INT REFERENCES users(id),\n"
        "    engagement_type VARCHAR(20),\n"
        "    created_at TIMESTAMP\n"
        ");"
    ),
    "seed_sql": (
        "INSERT INTO users (username, display_name, joined_at, is_verified) VALUES\n"
        "  ('alice_w', 'Alice Wang', '2023-01-10', true),\n"
        "  ('bob_j', 'Bob Johnson', '2023-03-15', false),\n"
        "  ('carol_s', 'Carol Smith', '2023-05-20', true),\n"
        "  ('dave_b', 'Dave Brown', '2023-07-01', false),\n"
        "  ('emma_d', 'Emma Davis', '2023-09-10', false),\n"
        "  ('frank_m', 'Frank Miller', '2023-11-05', true),\n"
        "  ('grace_l', 'Grace Lee', '2024-01-15', false),\n"
        "  ('henry_w', 'Henry Wilson', '2024-03-20', false),\n"
        "  ('iris_c', 'Iris Chen', '2024-05-01', true),\n"
        "  ('jack_t', 'Jack Taylor', '2024-07-10', false);\n\n"
        "-- Friendships (bidirectional): Alice<->Bob, Alice<->Carol, Bob<->Dave, Carol<->Emma\n"
        "INSERT INTO friendships (user_id, friend_id) VALUES\n"
        "  (1, 2), (2, 1),\n"
        "  (1, 3), (3, 1),\n"
        "  (2, 4), (4, 2),\n"
        "  (3, 5), (5, 3),\n"
        "  (4, 5), (5, 4),\n"
        "  (6, 7), (7, 6),\n"
        "  (6, 8), (8, 6),\n"
        "  (7, 9), (9, 7),\n"
        "  (8, 10), (10, 8),\n"
        "  (9, 10), (10, 9);\n\n"
        "-- Alice has 6 posts (meets threshold), others have fewer\n"
        "INSERT INTO posts (user_id, content, created_at, category) VALUES\n"
        "  (1, 'Post about AI', '2024-06-01 10:00', 'Tech'),\n"
        "  (1, 'Post about SQL', '2024-06-15 12:00', 'Tech'),\n"
        "  (1, 'Post about travel', '2024-07-01 09:00', 'Travel'),\n"
        "  (1, 'Post about cooking', '2024-07-15 14:00', 'Food'),\n"
        "  (1, 'Post about fitness', '2024-08-01 08:00', 'Health'),\n"
        "  (1, 'Post about music', '2024-08-15 16:00', 'Entertainment'),\n"
        "  (6, 'Frank on databases', '2024-06-10 11:00', 'Tech'),\n"
        "  (6, 'Frank on hiking', '2024-07-05 15:00', 'Travel'),\n"
        "  (6, 'Frank on reading', '2024-07-20 10:00', 'Books'),\n"
        "  (6, 'Frank on gaming', '2024-08-05 20:00', 'Entertainment'),\n"
        "  (6, 'Frank on cooking', '2024-08-20 18:00', 'Food'),\n"
        "  (6, 'Frank on yoga', '2024-09-01 07:00', 'Health'),\n"
        "  (2, 'Bob post 1', '2024-06-05 09:00', 'Tech'),\n"
        "  (2, 'Bob post 2', '2024-07-10 11:00', 'Travel'),\n"
        "  (2, 'Bob post 3', '2024-08-15 13:00', 'Food'),\n"
        "  (3, 'Carol post 1', '2024-06-20 10:00', 'Tech'),\n"
        "  (3, 'Carol post 2', '2024-07-25 12:00', 'Books'),\n"
        "  (3, 'Carol post 3', '2024-08-30 14:00', 'Health'),\n"
        "  (4, 'Dave post 1', '2024-07-01 11:00', 'Tech'),\n"
        "  (5, 'Emma post 1', '2024-07-15 09:00', 'Travel'),\n"
        "  (7, 'Grace post 1', '2024-08-01 10:00', 'Tech'),\n"
        "  (8, 'Henry post 1', '2024-08-15 11:00', 'Food'),\n"
        "  (9, 'Iris post 1', '2024-09-01 12:00', 'Health'),\n"
        "  (10, 'Jack post 1', '2024-09-15 13:00', 'Entertainment');\n\n"
        "-- Engagements: mix of friend and non-friend interactions\n"
        "-- Alice's posts get engagement from friends (Bob=2, Carol=3) and non-friends (4-10)\n"
        "INSERT INTO engagements (post_id, user_id, engagement_type, created_at)\n"
        "SELECT post_id, engager_id, eng_type, eng_time FROM (\n"
        "  VALUES\n"
        "    -- Friend engagements on Alice's posts\n"
        "    (1, 2, 'like', '2024-06-01 11:00'::timestamp),\n"
        "    (1, 3, 'comment', '2024-06-01 12:00'::timestamp),\n"
        "    (2, 2, 'like', '2024-06-15 13:00'::timestamp),\n"
        "    (2, 3, 'like', '2024-06-15 14:00'::timestamp),\n"
        "    -- Non-friend engagements on Alice's posts (these count for influence)\n"
        "    (1, 4, 'like', '2024-06-01 13:00'::timestamp),\n"
        "    (1, 5, 'comment', '2024-06-01 14:00'::timestamp),\n"
        "    (1, 6, 'like', '2024-06-01 15:00'::timestamp),\n"
        "    (1, 7, 'like', '2024-06-02 09:00'::timestamp),\n"
        "    (1, 8, 'comment', '2024-06-02 10:00'::timestamp),\n"
        "    (2, 4, 'like', '2024-06-16 09:00'::timestamp),\n"
        "    (2, 5, 'like', '2024-06-16 10:00'::timestamp),\n"
        "    (2, 6, 'comment', '2024-06-16 11:00'::timestamp),\n"
        "    (2, 7, 'like', '2024-06-16 12:00'::timestamp),\n"
        "    (3, 4, 'like', '2024-07-02 10:00'::timestamp),\n"
        "    (3, 5, 'comment', '2024-07-02 11:00'::timestamp),\n"
        "    (3, 8, 'like', '2024-07-02 12:00'::timestamp),\n"
        "    (3, 9, 'like', '2024-07-02 13:00'::timestamp),\n"
        "    (3, 10, 'comment', '2024-07-02 14:00'::timestamp),\n"
        "    (4, 6, 'like', '2024-07-16 09:00'::timestamp),\n"
        "    (4, 7, 'like', '2024-07-16 10:00'::timestamp),\n"
        "    (4, 8, 'comment', '2024-07-16 11:00'::timestamp),\n"
        "    (4, 9, 'like', '2024-07-16 12:00'::timestamp),\n"
        "    (4, 10, 'like', '2024-07-16 13:00'::timestamp),\n"
        "    (5, 4, 'like', '2024-08-02 09:00'::timestamp),\n"
        "    (5, 5, 'comment', '2024-08-02 10:00'::timestamp),\n"
        "    (5, 6, 'like', '2024-08-02 11:00'::timestamp),\n"
        "    (5, 9, 'like', '2024-08-02 12:00'::timestamp),\n"
        "    (5, 10, 'comment', '2024-08-02 13:00'::timestamp),\n"
        "    (6, 4, 'like', '2024-08-16 09:00'::timestamp),\n"
        "    (6, 5, 'like', '2024-08-16 10:00'::timestamp),\n"
        "    (6, 7, 'comment', '2024-08-16 11:00'::timestamp),\n"
        "    (6, 8, 'like', '2024-08-16 12:00'::timestamp),\n"
        "    (6, 9, 'like', '2024-08-16 13:00'::timestamp),\n"
        "    (6, 10, 'comment', '2024-08-16 14:00'::timestamp)\n"
        ") AS t(post_id, engager_id, eng_type, eng_time);"
    ),
    "index_sql": (
        "CREATE INDEX idx_friendships_user_friend ON friendships(user_id, friend_id);\n"
        "CREATE INDEX idx_engagements_post_user ON engagements(post_id, user_id);\n"
        "CREATE INDEX idx_posts_user ON posts(user_id);"
    ),
    "seed_sql_large": (
        "SELECT setseed(0.42);\n\n"
        "-- 10k users\n"
        "INSERT INTO users (username, display_name, joined_at, is_verified)\n"
        "SELECT 'user_' || i,\n"
        "  'User ' || i,\n"
        "  '2022-01-01'::date + (random() * 1000)::int,\n"
        "  random() < 0.1\n"
        "FROM generate_series(11, 10000) AS i;\n\n"
        "-- 1M friendships (~100 friends per user, bidirectional)\n"
        "-- Generate one direction, then insert reverse\n"
        "CREATE TEMP TABLE tmp_friends AS\n"
        "SELECT DISTINCT\n"
        "  (random() * 9999 + 1)::int AS user_id,\n"
        "  (random() * 9999 + 1)::int AS friend_id\n"
        "FROM generate_series(1, 600000)\n"
        "WHERE (random() * 9999 + 1)::int != (random() * 9999 + 1)::int;\n\n"
        "DELETE FROM tmp_friends WHERE user_id = friend_id;\n\n"
        "INSERT INTO friendships (user_id, friend_id)\n"
        "SELECT user_id, friend_id FROM tmp_friends\n"
        "ON CONFLICT DO NOTHING;\n\n"
        "INSERT INTO friendships (user_id, friend_id)\n"
        "SELECT friend_id, user_id FROM tmp_friends\n"
        "ON CONFLICT DO NOTHING;\n\n"
        "DROP TABLE tmp_friends;\n\n"
        "-- 500k posts\n"
        "INSERT INTO posts (user_id, content, created_at, category)\n"
        "SELECT\n"
        "  (random() * 9999 + 1)::int,\n"
        "  'Post content ' || i,\n"
        "  '2024-01-01'::timestamp + ((random() * 365)::int || ' days')::interval\n"
        "    + ((random() * 23)::int || ' hours')::interval,\n"
        "  (ARRAY['Tech','Travel','Food','Health','Entertainment','Books','Sports','Music'])[1 + (i % 8)]\n"
        "FROM generate_series(25, 500000) AS i;\n\n"
        "-- 2M engagements\n"
        "INSERT INTO engagements (post_id, user_id, engagement_type, created_at)\n"
        "SELECT\n"
        "  (random() * 499999 + 1)::int,\n"
        "  (random() * 9999 + 1)::int,\n"
        "  (ARRAY['like','comment'])[1 + (random())::int],\n"
        "  '2024-01-01'::timestamp + ((random() * 365)::int || ' days')::interval\n"
        "    + ((random() * 23)::int || ' hours')::interval\n"
        "FROM generate_series(1, 2000000);"
    ),
    "ground_truth_query": (
        "SELECT\n"
        "    u.display_name,\n"
        "    COUNT(DISTINCT p.id) AS post_count,\n"
        "    SUM(CASE WHEN fr.friend_id IS NULL THEN 1 ELSE 0 END) AS non_friend_engagements,\n"
        "    ROUND(\n"
        "        SUM(CASE WHEN fr.friend_id IS NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*),\n"
        "        2\n"
        "    ) AS non_friend_ratio\n"
        "FROM users u\n"
        "JOIN posts p ON p.user_id = u.id\n"
        "JOIN engagements e ON e.post_id = p.id\n"
        "LEFT JOIN friendships fr ON fr.user_id = u.id AND fr.friend_id = e.user_id\n"
        "GROUP BY u.id, u.display_name\n"
        "HAVING COUNT(DISTINCT p.id) >= 5 AND COUNT(*) >= 100\n"
        "ORDER BY non_friend_engagements DESC\n"
        "LIMIT 20;"
    ),
    "time_limit_ms": 15000,
}


def run(stdout, style):
    if Challenge.objects.filter(title=CHALLENGE["title"]).exists():
        stdout.write(f"  '{CHALLENGE['title']}' already exists, skipping.")
        return

    from api.views.challenges import _materialize_challenge

    challenge = Challenge.objects.create(**CHALLENGE)
    _materialize_challenge(challenge)

    stdout.write(style.SUCCESS(f"  Created '{CHALLENGE['title']}' challenge"))
